name: 'pagila_analytics'
version: '1.0.0'
config-version: 2

profile: 'pagila_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pagila_analytics:
    # Staging layer - materialized as views for easy refresh
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
    
    # Intermediate layer - views for flexibility
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate']
    
    # Marts layer - tables for performance
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts']
      dimensions:
        +tags: ['dimension']
      facts:
        +tags: ['fact']
    
    # Analytics layer - views for ad-hoc queries
    analytics:
      +materialized: view
      +schema: analytics
      +tags: ['analytics']

vars:
  # Date dimension configuration
  date_dim_start_date: '2005-01-01'
  date_dim_end_date: '2030-12-31'
