-- 1. Даём право создавать схемы во всей базе данных (если ещё не давали)
GRANT CREATE SCHEMA ON DATABASE PAGILA_SAKILA_DW TO ROLE AIRFLOW_DEV_ROLE;

-- 2. Явно даём право на владение схемой PAGILA_RAW (самая важная привилегия)
GRANT OWNERSHIP ON SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE REVOKE CURRENT GRANTS;

USE ROLE ACCOUNTADMIN;
USE DATABASE PAGILA_SAKILA_DW;

-- Создать схемы
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS DBT_ANALYTICS;

-- Дать права
GRANT USAGE ON SCHEMA STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA MARTS TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;

GRANT CREATE TABLE ON SCHEMA STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA MARTS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;

GRANT CREATE VIEW ON SCHEMA STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA MARTS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;

-- Дать ownership роли AIRFLOW_DEV_ROLE
GRANT OWNERSHIP ON SCHEMA STAGING TO ROLE AIRFLOW_DEV_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA MARTS TO ROLE AIRFLOW_DEV_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA ANALYTICS TO ROLE AIRFLOW_DEV_ROLE COPY CURRENT GRANTS;