-- 1. Проверьте, что роль AIRFLOW_DEV_ROLE и схема PAGILA_RAW существуют
USE ROLE ACCOUNTADMIN;
SHOW GRANTS TO ROLE AIRFLOW_DEV_ROLE;
USE DATABASE PAGILA_SAKILA_DW;
SHOW SCHEMAS LIKE 'PAGILA_RAW';

-- 2. Создайте отдельного пользователя для Airbyte (рекомендуется для безопасности)
CREATE USER IF NOT EXISTS AIRBYTE_SF_USER
  PASSWORD = '22890062'  -- Придумайте сложный пароль!
  DEFAULT_ROLE = AIRFLOW_DEV_ROLE
  DEFAULT_WAREHOUSE = COMPUTE_WH
  DEFAULT_NAMESPACE = 'PAGILA_SAKILA_DW.PAGILA_RAW';

-- 3. Дайте пользователю роль
GRANT ROLE AIRFLOW_DEV_ROLE TO USER AIRBYTE_SF_USER;