USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PAGILA_SAKILA_DW;

USE DATABASE PAGILA_SAKILA_DW;


CREATE SCHEMA IF NOT EXISTS PAGILA_RAW;
CREATE SCHEMA IF NOT EXISTS SAKILA_RAW;


CREATE SCHEMA IF NOT EXISTS DBT_ANALYTICS;


CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE ROLE IF NOT EXISTS AIRFLOW_DEV_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_DEV_ROLE;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_DEV_ROLE;

GRANT USAGE ON DATABASE PAGILA_SAKILA_DW TO ROLE AIRFLOW_DEV_ROLE;


GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT USAGE ON SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;


GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE TABLE ON SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;

GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT CREATE VIEW ON SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;


GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;


GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.PAGILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.SAKILA_RAW TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.DBT_ANALYTICS TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.STAGING TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.INTERMEDIATE TO ROLE AIRFLOW_DEV_ROLE;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PAGILA_SAKILA_DW.MARTS TO ROLE AIRFLOW_DEV_ROLE;


GRANT ROLE AIRFLOW_DEV_ROLE TO USER olejkus;


SHOW GRANTS TO ROLE AIRFLOW_DEV_ROLE;
SHOW SCHEMAS IN DATABASE PAGILA_SAKILA_DW;

-- as mention befor switch to other roles to test
-- USE ROLE AIRFLOW_DEV_ROLE;
-- USE WAREHOUSE COMPUTE_WH;
-- USE DATABASE PAGILA_SAKILA_DW;
-- SHOW SCHEMAS;
