version: 2

models:
  - name: stg_film
    description: "Staging model for films with cleaned and typed data"
    columns:
      - name: film_id
        description: "Primary key for film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Film title"
        tests:
          - not_null
      - name: rental_rate
        description: "Cost to rent the film"
      - name: duration_minutes
        description: "Length of the film in minutes"
  
  - name: stg_actor
    description: "Staging model for actors"
    columns:
      - name: actor_id
        description: "Primary key for actor"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Actor's full name (first + last)"
        tests:
          - not_null
  
  - name: stg_category
    description: "Staging model for film categories"
    columns:
      - name: category_id
        description: "Primary key for category"
        tests:
          - unique
          - not_null
      - name: category_name
        description: "Name of the category"
        tests:
          - not_null
  
  - name: stg_rental
    description: "Staging model for rental transactions"
    columns:
      - name: rental_id
        description: "Primary key for rental"
        tests:
          - unique
          - not_null
      - name: rental_date
        description: "Date and time when rental was made"
        tests:
          - not_null
      - name: customer_id
        description: "Foreign key to customer"
        tests:
          - not_null
  
  - name: stg_customer
    description: "Staging model for customers"
    columns:
      - name: customer_id
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Customer's full name"
        tests:
          - not_null
  
  - name: stg_inventory
    description: "Staging model for inventory items"
    columns:
      - name: inventory_id
        description: "Primary key for inventory"
        tests:
          - unique
          - not_null
      - name: film_id
        description: "Foreign key to film"
        tests:
          - not_null
  
  - name: stg_payment
    description: "Staging model for payment transactions"
    columns:
      - name: payment_id
        description: "Primary key for payment"
        tests:
          - unique
          - not_null
      - name: payment_amount
        description: "Amount paid"
        tests:
          - not_null
  
  - name: stg_address
    description: "Staging model for addresses"
    columns:
      - name: address_id
        description: "Primary key for address"
        tests:
          - unique
          - not_null
  
  - name: stg_city
    description: "Staging model for cities"
    columns:
      - name: city_id
        description: "Primary key for city"
        tests:
          - unique
          - not_null
      - name: city_name
        description: "Name of the city"
        tests:
          - not_null
