{{
    config(
        materialized='view',
        tags=['analytics', 'actor']
    )
}}

-- Top Rented Actors Analysis
-- Identifies the most popular actors based on rental counts

with rentals as (
    select * from {{ ref('stg_rental') }}
),

inventory as (
    select * from {{ ref('stg_inventory') }}
),

film_actor as (
    select * from {{ ref('stg_film_actor') }}
),

actors as (
    select * from {{ ref('stg_actor') }}
),

actor_rentals as (
    select
        a.actor_id,
        a.full_name as actor_name,
        a.first_name,
        a.last_name,
        count(distinct r.rental_id) as total_rentals,
        count(distinct fa.film_id) as films_appeared_in,
        
        -- Revenue generated by actor's films
        round(avg(r.rental_duration_hours), 2) as avg_rental_duration_hours
        
    from actors a
    inner join film_actor fa on a.actor_id = fa.actor_id
    inner join inventory i on fa.film_id = i.film_id
    inner join rentals r on i.inventory_id = r.inventory_id
    group by 
        a.actor_id,
        a.full_name,
        a.first_name,
        a.last_name
    order by total_rentals desc
)

select * from actor_rentals
